version: "2"
services:
  api_service:
    container_name: api_service
    build:
      context: api_service
    image: api_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Api Service"
      STOCK_SERVICE_URL: "http://stock_service:81"
      AUTH_SERVICE_URL: "http://auth_service:82"
      LOG_SERVICE_URL: "http://log_service:83"
    ports:
      - "80:80"
    networks:
      - app-network

  stock_service:
    container_name: stock_service
    build:
      context: stock_service
    image: stock_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Stock Service"
      API_SERVICE_URL: "http://api_service:80"
      LOG_SERVICE_URL: "http://log_service:83"
    ports:
      - "81:81"
    networks:
      - app-network

  auth_service:
    container_name: auth_service
    build:
      context: auth_service
    image: auth_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Auth Service"
      USERNAME: "user@stock.com"
      PASSWORD: "stock_is_up_100%"
      API_SERVICE_URL: "http://api_service:80"
      LOG_SERVICE_URL: "http://log_service:83"
    ports:
      - "82:82"
    networks:
      - app-network

  log_service:
    container_name: log_service
    build:
      context: log_service
    image: log_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Log Service"
      API_SERVICE_URL: "http://api_service:80"
      AUTH_SERVICE_URL: "http://auth_service:81"
      STOCK_SERVICE_URL: "http://stock_service:82"
    ports:
      - "83:83"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: frontend
    image: frontend
    depends_on:
      - api_service
      - stock_service
      - auth_service
      - log_service
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
